// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6LCjifSQRxp9K9uaZnikpIGpbzBFkc3M',
    appId: '1:208149054118:web:84f077babc43a5b7956a67',
    messagingSenderId: '208149054118',
    projectId: 'sgras-app',
    authDomain: 'sgras-app.firebaseapp.com',
    storageBucket: 'sgras-app.firebasestorage.app',
    measurementId: 'G-9LL7FNBDWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeBJk1sE4jICBEnoxV27CTDOdXxqRMFQI',
    appId: '1:208149054118:android:e213ae589d80a7ec956a67',
    messagingSenderId: '208149054118',
    projectId: 'sgras-app',
    storageBucket: 'sgras-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZyBR3TQzX1FSEENA6QzfLNtI4XiPX3PQ',
    appId: '1:208149054118:ios:df22a337304e1545956a67',
    messagingSenderId: '208149054118',
    projectId: 'sgras-app',
    storageBucket: 'sgras-app.firebasestorage.app',
    iosBundleId: 'com.zaygon.skydiving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZyBR3TQzX1FSEENA6QzfLNtI4XiPX3PQ',
    appId: '1:208149054118:ios:c9b7daf3ee1b7542956a67',
    messagingSenderId: '208149054118',
    projectId: 'sgras-app',
    storageBucket: 'sgras-app.firebasestorage.app',
    iosBundleId: 'com.zaygon.skydiving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6LCjifSQRxp9K9uaZnikpIGpbzBFkc3M',
    appId: '1:208149054118:web:5b794f57ad009ffc956a67',
    messagingSenderId: '208149054118',
    projectId: 'sgras-app',
    authDomain: 'sgras-app.firebaseapp.com',
    storageBucket: 'sgras-app.firebasestorage.app',
    measurementId: 'G-M8VBVM4V2N',
  );
}
